# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guesswidth < Formula
  desc "guesses the column position for fixed-width formats(fwf)"
  homepage "https://noborus.github.io/"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/noborus/guesswidth/releases/download/v0.4.0/guesswidth_0.4.0_darwin_amd64.tar.gz"
      sha256 "cf7820be142dd142f27aa9b0a3571deb3bcac828bd145415629bc741372b0751"

      def install
        bin.install "guesswidth"
      end
    end
    on_arm do
      url "https://github.com/noborus/guesswidth/releases/download/v0.4.0/guesswidth_0.4.0_darwin_arm64.tar.gz"
      sha256 "953a9b2278e2cc63dad6065ceb2460858651abc81c84c9961b1f0745238c0de9"

      def install
        bin.install "guesswidth"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noborus/guesswidth/releases/download/v0.4.0/guesswidth_0.4.0_linux_amd64.tar.gz"
        sha256 "b4b6ddc15478cd812dfc1829c6604b2884c40b58c2e06a32e98fab87076d299c"

        def install
          bin.install "guesswidth"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/noborus/guesswidth/releases/download/v0.4.0/guesswidth_0.4.0_linux_arm64.tar.gz"
        sha256 "75a70bcef7c14dc227ad09c76405bc16e2e9e9f87f10000601b244779b4a5a33"

        def install
          bin.install "guesswidth"
        end
      end
    end
  end
end
