# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Guesswidth < Formula
  desc "guesses the column position for fixed-width formats (fwf)"
  homepage "https://noborus.github.io/"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/guesswidth/releases/download/v0.5.0/guesswidth_0.5.0_darwin_amd64.tar.gz"
      sha256 "46014e57c74155fc5c71576eb1db1fc2f0a5dd6d61397cf7eed7921f98e4c361"

      define_method(:install) do
        bin.install "guesswidth"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/guesswidth/releases/download/v0.5.0/guesswidth_0.5.0_darwin_arm64.tar.gz"
      sha256 "56caa84a4f87e5bf6f5b2cd7c82ce3227105a50027de3a9395fbe79432b1a82b"

      define_method(:install) do
        bin.install "guesswidth"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/guesswidth/releases/download/v0.5.0/guesswidth_0.5.0_linux_amd64.tar.gz"
      sha256 "8ea34b07b4da7ff013ceea8be8b32c34b68e477d86011f0167b9a39c23da4f47"
      define_method(:install) do
        bin.install "guesswidth"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/guesswidth/releases/download/v0.5.0/guesswidth_0.5.0_linux_arm64.tar.gz"
      sha256 "188ea3979c123c89c610b8d099d6b196249682574b990053a2c421b1c64b0d60"
      define_method(:install) do
        bin.install "guesswidth"
      end
    end
  end
end
