# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JpugDocTool < Formula
  desc "jpug-doc tool"
  homepage "https://github.com/noborus/jpug-doc-tool"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.3.1/jpug-doc-tool_0.3.1_darwin_amd64.tar.gz"
      sha256 "07c909bc759a5f689306f09bce3d50174fac232fbc26501fce47cd6afdb1f2b2"

      def install
        bin.install "jpug-doc-tool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.3.1/jpug-doc-tool_0.3.1_darwin_arm64.tar.gz"
      sha256 "f10263f2ddd4baff2928712c92ef5a8031c44694386fd3f6e47db915f92aa344"

      def install
        bin.install "jpug-doc-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.3.1/jpug-doc-tool_0.3.1_linux_arm64.tar.gz"
      sha256 "82889adfc5538b4d86807aba93aa9501315cd6740996bb942703f216a33138de"

      def install
        bin.install "jpug-doc-tool"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.3.1/jpug-doc-tool_0.3.1_linux_amd64.tar.gz"
      sha256 "f4e7873aa39cd5a57d68c4098a2e53bc8d225935a983f98fb6375d432c8c70fe"

      def install
        bin.install "jpug-doc-tool"
      end
    end
  end

  test do
    system "#{bin}/jpug-doc-tool --version"
  end
end
