# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JpugDocTool < Formula
  desc "PostgreSQL Japanese manual translation tool"
  homepage "https://github.com/noborus/jpug-doc-tool"
  version "0.7.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.7.0/jpug-doc-tool_0.7.0_darwin_amd64.tar.gz"
      sha256 "0394f9826776e208c66567740bccbd54cce61c7cb3c51651af903c2bc59218e4"

      define_method(:install) do
        bin.install "jpug-doc-tool"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.7.0/jpug-doc-tool_0.7.0_darwin_arm64.tar.gz"
      sha256 "913392b16f2161474c03ea5a28335adcac9b9083631a7399f8c7358ddc8f5ca9"

      define_method(:install) do
        bin.install "jpug-doc-tool"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.7.0/jpug-doc-tool_0.7.0_linux_amd64.tar.gz"
      sha256 "0f2f4cca8b9f4b8f9f57f821b83d7616f7adc44d4759c99eddab126c94a112ce"
      define_method(:install) do
        bin.install "jpug-doc-tool"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/jpug-doc-tool/releases/download/v0.7.0/jpug-doc-tool_0.7.0_linux_arm64.tar.gz"
      sha256 "2962e2ffd7d21e6221faa2d5710381f74ca8a1ee2847e42572db0c79623e8689"
      define_method(:install) do
        bin.install "jpug-doc-tool"
      end
    end
  end

  test do
    system "#{bin}/jpug-doc-tool --version"
  end
end
