# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdtsql < Formula
  desc "Execute SQL to markdown table and convert to other format"
  homepage "https://github.com/noborus/mdtsql"
  version "0.0.5"
  depends_on :linux

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/mdtsql/releases/download/v0.0.5/mdtsql_0.0.5_linux_amd64.tar.gz"
      sha256 "ca011547295d47c65c09f56e88e0c750dbc230fc5502c3709822e512317a5d4a"

      def install
        bin.install "mdtsql"
      end
    end
  end
end
