# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdviewer < Formula
  desc "markdown viewer"
  homepage "https://github.com/noborus/mdviewer"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/mdviewer/releases/download/v0.2.0/mdviewer_0.2.0_darwin_amd64.zip"
      sha256 "f500f759b1db4abeac752fc4b7188e8763da50be0192cb833f470b005a0104f8"

      define_method(:install) do
        bin.install "mdviewer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/mdviewer/releases/download/v0.2.0/mdviewer_0.2.0_darwin_arm64.zip"
      sha256 "dae9c040584657bdac70fa5efca4f3b5ba830abead97b7d72d80f6f2f08383f0"

      define_method(:install) do
        bin.install "mdviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/mdviewer/releases/download/v0.2.0/mdviewer_0.2.0_linux_amd64.zip"
      sha256 "43104fef4bd5ec1c80ff3b59dc5eaa6404bace9d20afa7457b44cd2077d92795"
      define_method(:install) do
        bin.install "mdviewer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/mdviewer/releases/download/v0.2.0/mdviewer_0.2.0_linux_arm.zip"
      sha256 "c061a1a9d065ead8bba3b5d484a9b4d528c0b6621571e20a25687e104bcbcec3"
      define_method(:install) do
        bin.install "mdviewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/mdviewer/releases/download/v0.2.0/mdviewer_0.2.0_linux_arm64.zip"
      sha256 "5dbc4886f0d66dcfe06fb71261866f8b8d42d311bdaab13c42687adf2749e593"
      define_method(:install) do
        bin.install "mdviewer"
      end
    end
  end

  test do
    system "#{bin}/mdviewer --version"
  end
end
