# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdviewer < Formula
  desc "markdown viewer"
  homepage "https://github.com/noborus/mdviewer"
  version "0.1.1-alpha.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noborus/mdviewer/releases/download/v0.1.1-alpha.2/mdviewer_0.1.1-alpha.2_darwin_arm64.zip"
      sha256 "a68502b629ae9793003d501eee99b78e2d4b17679a6bce4cdf5e9c9e72e4a22c"

      def install
        bin.install "mdviewer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/mdviewer/releases/download/v0.1.1-alpha.2/mdviewer_0.1.1-alpha.2_darwin_amd64.zip"
      sha256 "8f4224c90f0d2b1e09cd84343730697b5e3f4fda8fb88554eabc752e2606cf94"

      def install
        bin.install "mdviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/mdviewer/releases/download/v0.1.1-alpha.2/mdviewer_0.1.1-alpha.2_linux_arm.zip"
      sha256 "4e2cc32c2573a6f72253bc3545696a0419eff839ab6009bee1942f240d3a42f7"

      def install
        bin.install "mdviewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/mdviewer/releases/download/v0.1.1-alpha.2/mdviewer_0.1.1-alpha.2_linux_arm64.zip"
      sha256 "0f4c7b386e0b789850308a5d665e94251d875db3b5093eaefbfe72e85a61fee3"

      def install
        bin.install "mdviewer"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/mdviewer/releases/download/v0.1.1-alpha.2/mdviewer_0.1.1-alpha.2_linux_amd64.zip"
      sha256 "1b3c6375fd4c0270ed3678c730b080c766a706887224a41139a1010a5ce15557"

      def install
        bin.install "mdviewer"
      end
    end
  end

  test do
    system "#{bin}/mdviewer --version"
  end
end
