# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Feature rich terminal pager"
  homepage "https://github.com/noborus/ov"
  version "0.12.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.12.1/ov_0.12.1_darwin_amd64.zip"
      sha256 "e786b219cf944ad4c0d4676bef74cace97ea7ef1254f3e38a9ede919be2b969d"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ov/releases/download/v0.12.1/ov_0.12.1_darwin_arm64.zip"
      sha256 "2472ee3baf9a58d5308de5875191c92961049846899e9345753d6c92d5b8e831"

      def install
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.12.1/ov_0.12.1_linux_arm.zip"
      sha256 "da2750588da49f91c844c836666fddab5b11ef282ed5b0f1d70f3e7be95618aa"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.12.1/ov_0.12.1_linux_amd64.zip"
      sha256 "541e179c3f310dde42a2056489c05377dd515e4458638f3a818072718c0a3d30"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.12.1/ov_0.12.1_linux_arm64.zip"
      sha256 "b459c926bbbc7a49c442244e7e21e63b6b0c78142d7772c90cc4f5725ef0700c"

      def install
        bin.install "ov"
      end
    end
  end

  test do
    system "#{bin}/ov --version"
  end
end
