# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Feature rich terminal pager"
  homepage "https://github.com/noborus/ov"
  version "0.34.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.34.1/ov_0.34.1_darwin_amd64.zip"
      sha256 "5a4a05cba26b640663ed3c854e314faf2527b2e25d6028ee0ac10b8bd7d6b679"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ov/releases/download/v0.34.1/ov_0.34.1_darwin_arm64.zip"
      sha256 "627d11dc708b808266209fcb335b2f2dd6104897899db902ae83e91f4a24fa84"

      def install
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.34.1/ov_0.34.1_linux_amd64.zip"
      sha256 "d975f2fe3d352adea088949afc4a81b82b25189a7c5d8e64256695207703dd71"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.34.1/ov_0.34.1_linux_arm.zip"
      sha256 "e0df3132e4fd80eda69f78bfbb82b780c268ca2e42f89876cb60fceed40d5b8f"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.34.1/ov_0.34.1_linux_arm64.zip"
      sha256 "a7e94b5a49370123d6139ec567305526b35e6c50f319cec215ab879a778cc2a6"

      def install
        bin.install "ov"
      end
    end
  end

  test do
    system "#{bin}/ov --version"
  end
end
