# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Feature rich terminal pager"
  homepage "https://github.com/noborus/ov"
  version "0.23.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ov/releases/download/v0.23.0/ov_0.23.0_darwin_arm64.zip"
      sha256 "e92216b0135cc2ac9893c57e629eac9edec68307a84460c4131681e3bdd73b74"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.23.0/ov_0.23.0_darwin_amd64.zip"
      sha256 "96ffeba2e66288b310d3d6f182edfe4fea7fcb9c364c60afe4bfaa86264bfb1d"

      def install
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.23.0/ov_0.23.0_linux_arm64.zip"
      sha256 "6509d0699a6a4e72aaaa10aa7414b098ef7a9de80b219c53bc83d80a77d4c8e2"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ov/releases/download/v0.23.0/ov_0.23.0_linux_amd64.zip"
      sha256 "422d8e9171dffbfa2edc0ee984d41903a40e90aa6a1b20d4f2bcb7dcbbd5028c"

      def install
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ov/releases/download/v0.23.0/ov_0.23.0_linux_arm.zip"
      sha256 "5be8244d9727a876fbc6895a273c61429fbf0a14990a7e4bbe2f1c5d6e093158"

      def install
        bin.install "ov"
      end
    end
  end

  test do
    system "#{bin}/ov --version"
  end
end
