# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ovcs < Formula
  desc "Feature rich terminal pager"
  homepage "https://github.com/noborus/ovcs"
  version "0.9.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ovcs/releases/download/v0.9.5/ovcs_0.9.5_darwin_arm64.zip"
      sha256 "fb58260524231e1e398662801d581a01b96818750b9c68bd679121b7148783f2"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ovcs/releases/download/v0.9.5/ovcs_0.9.5_darwin_amd64.zip"
      sha256 "8f7a766a9bf2a73724cd0114e679dadfcf24c96dd92b8117cd7f538e65164220"

      def install
        bin.install "ovcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ovcs/releases/download/v0.9.5/ovcs_0.9.5_linux_amd64.zip"
      sha256 "99ef8c5199429a4f7bd30756a3e8c2989d187395b181818ec5a3e8bbd346a55b"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ovcs/releases/download/v0.9.5/ovcs_0.9.5_linux_arm.zip"
      sha256 "4b124ef855e74c54151bf63634b4736fe9361cac0f15211a8dfbbfe2dc5c9757"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ovcs/releases/download/v0.9.5/ovcs_0.9.5_linux_arm64.zip"
      sha256 "768e4e1cf085207c9747c4510a9d20b614a87745efaa5ce61a4913823b295395"

      def install
        bin.install "ovcs"
      end
    end
  end

  test do
    system "#{bin}/ovcs version"
  end
end
