# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ovcs < Formula
  desc "The client/server of the terminal pager ov"
  homepage "https://github.com/noborus/ovcs"
  version "0.16.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ovcs/releases/download/v0.16.1/ovcs_0.16.1_darwin_amd64.zip"
      sha256 "184e1f097f7edb0e0727b8a2c1b6c8d67ae7f95da9b4afb1e4a12aa856bf05fd"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ovcs/releases/download/v0.16.1/ovcs_0.16.1_darwin_arm64.zip"
      sha256 "9a0fac4bb8020974caecf340d82b84731b6830c348661f7ad5f19751dccf1ec0"

      def install
        bin.install "ovcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ovcs/releases/download/v0.16.1/ovcs_0.16.1_linux_amd64.zip"
      sha256 "81f652b76e538907577d0946640492f24fdd8c2ca5dd66c9ae1101fb301f103b"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ovcs/releases/download/v0.16.1/ovcs_0.16.1_linux_arm.zip"
      sha256 "5d6e186449be7edaf0a8dd4ae3812f5f34f640debf38a1508bc811979e08800b"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ovcs/releases/download/v0.16.1/ovcs_0.16.1_linux_arm64.zip"
      sha256 "3b7319ca20825f5f8ffc24b45240fa3b65825e8f056d1c786abc336ac148e316"

      def install
        bin.install "ovcs"
      end
    end
  end

  test do
    system "#{bin}/ovcs version"
  end
end
