# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ovcs < Formula
  desc "The client/server of the terminal pager ov"
  homepage "https://github.com/noborus/ovcs"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ovcs/releases/download/v0.15.0/ovcs_0.15.0_darwin_amd64.zip"
      sha256 "347cb1c78e4d8d5da5d5d995b1324a73625e62514450a35ac7e37851bc05a17b"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/ovcs/releases/download/v0.15.0/ovcs_0.15.0_darwin_arm64.zip"
      sha256 "9f17acd3c422feae1e338c39a416ed58f4d7a1d205c70a970e27b2fc5f4162b3"

      def install
        bin.install "ovcs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ovcs/releases/download/v0.15.0/ovcs_0.15.0_linux_arm.zip"
      sha256 "057f67e9992f61ccc66df7e3af625f41ec812cd186ad88e0c314d787d02dbe52"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/ovcs/releases/download/v0.15.0/ovcs_0.15.0_linux_amd64.zip"
      sha256 "af94ec3cb354a8128185491b96116516a09d3bf9cc9bd207a1883c46c82525bf"

      def install
        bin.install "ovcs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/ovcs/releases/download/v0.15.0/ovcs_0.15.0_linux_arm64.zip"
      sha256 "c6c06f1a9d627c903f8809a3c0830ebb8df358135d9be1c9ae75c95938222799"

      def install
        bin.install "ovcs"
      end
    end
  end

  test do
    system "#{bin}/ovcs version"
  end
end
