# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsp < Formula
  desc "PostgreSQL Stat Progress CLI Monitor"
  homepage "https://github.com/noborus/pgsp"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.5/pgsp_0.0.5_darwin_amd64.zip"
      sha256 "d4d97cc6577ad0389a7ae9242928286679fe9acb24a71d1b0a444104e20e6f92"

      def install
        bin.install "pgsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.5/pgsp_0.0.5_darwin_arm64.zip"
      sha256 "ad22e8a8dcc42e75a412390cd9ac6abb64191cc2879459940142bad3e00ed378"

      def install
        bin.install "pgsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.5/pgsp_0.0.5_linux_arm.zip"
      sha256 "efb71d8dbc3db04ea5eb0171eb97d54362b6ddd0f0ec29384a2a67cac6c6f1f4"

      def install
        bin.install "pgsp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.5/pgsp_0.0.5_linux_amd64.zip"
      sha256 "c661b7b8022f8712b623469180255799b01beb7acc2d454530f696ed42cb1d1e"

      def install
        bin.install "pgsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.5/pgsp_0.0.5_linux_arm64.zip"
      sha256 "318eda884e57a864245a0567874d9e9269b3a0487aaaf63b957a3469a7d453ab"

      def install
        bin.install "pgsp"
      end
    end
  end

  test do
    system "#{bin}/pgsp --version"
  end
end
