# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsp < Formula
  desc "PostgreSQL Stat Progress CLI Monitor"
  homepage "https://github.com/noborus/pgsp"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.3/pgsp_0.0.3_darwin_amd64.zip"
      sha256 "20a0a662d61f15e49cda03402eab31c6f4d06da02e9c8c904f3a8aeab962bfa1"

      def install
        bin.install "pgsp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.3/pgsp_0.0.3_darwin_arm64.zip"
      sha256 "84559fee74c195ed69add4a9cfb187fc7395e6f0810761578709a7da1ef83fe0"

      def install
        bin.install "pgsp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.3/pgsp_0.0.3_linux_amd64.zip"
      sha256 "8224757a7b4578026643f9616a3df3c3df907ab929b8021ae675095911f282a1"

      def install
        bin.install "pgsp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.3/pgsp_0.0.3_linux_arm64.zip"
      sha256 "f75f2cd7fefb3157a23b25344f525c23bdd544484bea585035f09995b885423e"

      def install
        bin.install "pgsp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.3/pgsp_0.0.3_linux_arm.zip"
      sha256 "3249e9747ec639daea85b3bcdfcdffcb7f631ab02d38d6b980e528b95d294f6d"

      def install
        bin.install "pgsp"
      end
    end
  end

  test do
    system "#{bin}/pgsp --version"
  end
end
