# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pgsp < Formula
  desc "PostgreSQL Stat Progress CLI Monitor"
  homepage "https://github.com/noborus/pgsp"
  version "0.0.1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.1/pgsp_0.0.1_darwin_amd64.zip"
      sha256 "bbeab66b5c9df36a831c84dc6f006741230fb20d110bdc52cf79609fdf5acd18"
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.1/pgsp_0.0.1_darwin_arm64.zip"
      sha256 "c6fbc2e6eb89598ae6e768c66c5a5a5384765f4f3e14d30b5cefa12d78c42348"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.1/pgsp_0.0.1_linux_amd64.zip"
      sha256 "ee99dcfa5d5d767b39f0249deb5891f87f3eecbe4c4972274656b935631e0d81"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.1/pgsp_0.0.1_linux_arm.zip"
      sha256 "c180d4adcd246d54cf98bbbf24c2eb28fcde7e788a3c48279cbe9ff623b8c46e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/pgsp/releases/download/v0.0.1/pgsp_0.0.1_linux_arm64.zip"
      sha256 "8ce3bebe6f73ee6ce053c68a7fb8aaac565183b68bdc56098fa2b478099d73e6"
    end
  end

  def install
    bin.install "pgsp"
  end

  test do
    system "#{bin}/pgsp --version"
  end
end
