# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xlsxsql < Formula
  desc "Execute SQL to xlsx and convert to other format"
  homepage "https://github.com/noborus/xlsxsql"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.5.3/xlsxsql_0.5.3_Darwin_x86_64.tar.gz"
      sha256 "61a74873a7251d575472ced64743898093b153f97785be7cb0de20f590e2bed4"

      define_method(:install) do
        bin.install "xlsxsql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.5.3/xlsxsql_0.5.3_Darwin_arm64.tar.gz"
      sha256 "91c07b03a1136b743516329d168932be961e3a8898defb465e071c1da85f5881"

      define_method(:install) do
        bin.install "xlsxsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.5.3/xlsxsql_0.5.3_Linux_x86_64.tar.gz"
      sha256 "b8449eebd9b9ee5b225f95b70416f5bc6b65f78f65e5e7fd7eda532fdc641446"
      define_method(:install) do
        bin.install "xlsxsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.5.3/xlsxsql_0.5.3_Linux_arm64.tar.gz"
      sha256 "3af083d2c81e40846fa9fab7bc889acb3cfac402e940c275cdc9dc5f1da02c2f"
      define_method(:install) do
        bin.install "xlsxsql"
      end
    end
  end
end
