# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xlsxsql < Formula
  desc "Execute SQL to xlsx and convert to other format"
  homepage "https://github.com/noborus/xlsxsql"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.4.0/xlsxsql_0.4.0_Darwin_arm64.tar.gz"
      sha256 "1e573a77f5a7828c5c49c8c78ecbda401d2cbe091dde2d3ee18ebc4abe3d9ab3"

      def install
        bin.install "xlsxsql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.4.0/xlsxsql_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "2e1f7beb013b7534d00c17eef78ee40779dbe312dd7477c6f4bf513b9a616568"

      def install
        bin.install "xlsxsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.4.0/xlsxsql_0.4.0_Linux_arm64.tar.gz"
      sha256 "e178213df121dcdbdf3984740bf880dfd54873b1c42b7cbea066600dc5a2f3e7"

      def install
        bin.install "xlsxsql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.4.0/xlsxsql_0.4.0_Linux_x86_64.tar.gz"
      sha256 "e95ffce1780060cdb501eeca00b7d3af4d300d0917809d55b9a674708f387a15"

      def install
        bin.install "xlsxsql"
      end
    end
  end
end
