# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xlsxsql < Formula
  desc "Execute SQL to xlsx and convert to other format"
  homepage "https://github.com/noborus/xlsxsql"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.3.0/xlsxsql_0.3.0_Darwin_arm64.tar.gz"
      sha256 "6a05ea241282a0f99fbcc106577ede751a4e0910dfb89a600f4eaab4db3a1dd1"

      def install
        bin.install "xlsxsql"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.3.0/xlsxsql_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "a31522a4cd20206deb231a51462d53d7cc6b20791bf54ecd3b56fe682ad8b7be"

      def install
        bin.install "xlsxsql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.3.0/xlsxsql_0.3.0_Linux_x86_64.tar.gz"
      sha256 "a294340933307b07aef2c4675df6f2ebb1d3ad47294edaffc974298733c48389"

      def install
        bin.install "xlsxsql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/noborus/xlsxsql/releases/download/v0.3.0/xlsxsql_0.3.0_Linux_arm64.tar.gz"
      sha256 "1830d22411fec9a15634dbba7858b92d6eb0db099c8af4eb0a788179d32dd806"

      def install
        bin.install "xlsxsql"
      end
    end
  end
end
